package com.hospital.queue.Entities;

public enum Department {

    GENERAL_MEDICINE,
    GENERAL_SURGERY,
    PEDIATRICS,
    OBSTETRICS_GYNECOLOGY,
    ORTHOPEDICS,
    CARDIOLOGY,
    NEUROLOGY,
    NEPHROLOGY,
    PULMONOLOGY,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    DERMATOLOGY,
    PSYCHIATRY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ENT,
    UROLOGY,
    DENTISTRY,
    ANESTHESIOLOGY,
    PHYSIOTHERAPY,


    PATHOLOGY,
    RADIOLOGY,
    CRITICAL_CARE,
    BLOOD_BANK,


    CARDIOTHORACIC_SURGERY,
    NEUROSURGERY,
    PLASTIC_SURGERY,
    PEDIATRIC_SURGERY,
    RHEUMATOLOGY,
    GERIATRICS,
    INFECTIOUS_DISEASES
}
